version: '3'

services:
  api-solid-pg:
    image: bitnami/postgresql
    ports:
      - 5432:5432
    environment:
      - POSTGRESQL_DATABASE=api-gympass
      - POSTGRESQL_USER=docker
      - POSTGRESQL_PASSWORD=docker
    